publish:
  address: 224.5.23.1:10003
global:
  yellow-card-duration: 2m
normal:
  half-duration: 5m
  half-time-duration: 5m
  timeout-duration: 5m
  timeouts: 4
  break-after: 5m
overtime:
  half-duration: 2m30s
  half-time-duration: 2m
  timeout-duration: 5m
  timeouts: 2
  break-after: 2m