version: 2
jobs:
  frontend:
    docker:
    - image: circleci/node:10.8.0
    steps:
    - checkout
    - run:
        name: "Install dependencies"
        command: npm install
        working_directory: ui
    - run:
        name: "Run tests"
        command: npm test
        working_directory: ui
    - run:
        name: "Build"
        command: npm run build
        working_directory: ui
    - persist_to_workspace:
        root: .
        paths:
        - ui/dist/*

  backend:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: go get -v -t -d ./...
    - run: go test -v ./...
    - run:
        working_directory: cmd/ssl-game-controller
        command: |
          go get -v github.com/gobuffalo/packr/packr
          GOOS=linux GOARCH=amd64 packr build -o ../../release/linux/ssl-game-controller
          GOOS=windows GOARCH=amd64 packr build -o ../../release/windows/ssl-game-controller.exe
          GOOS=darwin GOARCH=amd64 packr build -o ../../release/darwin/ssl-game-controller
    - persist_to_workspace:
        root: .
        paths:
        - release/*

  publish-github-release:
    docker:
    - image: circleci/golang:1.10
    steps:
    - attach_workspace:
        at: .
    - run:
        name: "Publish Release on GitHub"
        command: |
          go get github.com/tcnksm/ghr
          VERSION=latest
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./release/

workflows:
  version: 2
  main:
    jobs:
    - frontend
    - backend:
        requires:
        - frontend
    - publish-github-release:
        requires:
        - backend
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
