version: 2
jobs:
  ui:
    docker:
    - image: circleci/node:10.8.0
    steps:
    - attach_workspace:
        at: ./ui/dist
    - checkout
    - run: npm install
    - run: npm test
    - run: npm run build

  build:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - attach_workspace:
        at: ./ui/dist
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -v ./...

workflows:
  version: 2
  release:
    jobs:
    - ui
    - build:
        requires:
        - ui