version: 2
jobs:
  frontend:
    docker:
    - image: circleci/node:10.8.0
    steps:
    - checkout
    - attach_workspace:
        at: ./ui/dist
    - run:
        name: "Install dependencies"
        command: npm install
        working_directory: ui
    - run:
        name: "Run tests"
        command: npm test
        working_directory: ui
    - run:
        name: "Build"
        command: npm run build
        working_directory: ui

  backend:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - checkout
    - attach_workspace:
        at: ./ui/dist
    - run: go get -v -t -d ./...
    - run: go test -v ./...

  deploy:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - checkout
    - attach_workspace:
        at: ./ui/dist
    - run: go get -v -t -d ./...
    - run: ./release.sh
    - run: ll release && tree release


workflows:
  version: 2
  release:
    jobs:
    - frontend
    - backend
    - deploy:
        requires:
        - frontend