version: 2
jobs:
  frontend:
    docker:
    - image: circleci/node:10.8.0
    steps:
    - checkout
    - attach_workspace:
        at: ./ui/dist
    - run:
        name: "Install dependencies"
        command: npm install
        working_directory: ui
    - run:
        name: "Run tests"
        command: npm test
        working_directory: ui
    - run:
        name: "Build"
        command: npm run build
        working_directory: ui

  backend:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - checkout
    - attach_workspace:
        at: ./ui/dist
    - attach_workspace:
        at: ./release
    - run: go get -v -t -d ./...
    - run: go test -v ./...
    - run:
        working_directory: cmd/ssl-game-controller
        command: |
          go get -v github.com/gobuffalo/packr/...
          GOOS=linux GOARCH=amd64 packr build -o ../../release/linux/ssl-game-controller
          GOOS=windows GOARCH=amd64 packr build -o ../../release/windows/ssl-game-controller.exe
          GOOS=darwin GOARCH=amd64 packr build -o ../../release/darwin/ssl-game-controller

  deploy:
    docker:
    - image: circleci/golang:1.10

    working_directory: /go/src/github.com/g3force/ssl-game-controller
    steps:
    - attach_workspace:
        at: ./release
    - run: ll release && tree release

  publish-github-release:
    docker:
    - image: circleci/golang:1.8
    steps:
    - attach_workspace:
        at: ./release
    - run:
        name: "Publish Release on GitHub"
        command: |
          go get github.com/tcnksm/ghr
          VERSION=latest
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./release/

workflows:
  version: 2
  release:
    jobs:
    - frontend
    - backend:
        requires:
        - frontend
    - deploy:
        requires:
        - backend
    - publish-github-release:
        requires:
        - backend