{
  "gameEventBehavior": {
    "AIMLESS_KICK": "GAME_EVENT_BEHAVIOR_ON",
    "ATTACKER_DOUBLE_TOUCHED_BALL": "GAME_EVENT_BEHAVIOR_ON",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "GAME_EVENT_BEHAVIOR_ON",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "GAME_EVENT_BEHAVIOR_ON",
    "ATTACKER_TOUCHED_OPPONENT_IN_DEFENSE_AREA": "GAME_EVENT_BEHAVIOR_ON",
    "ATTACKER_TOUCHED_OPPONENT_IN_DEFENSE_AREA_SKIPPED": "GAME_EVENT_BEHAVIOR_ON",
    "BALL_LEFT_FIELD_GOAL_LINE": "GAME_EVENT_BEHAVIOR_ON",
    "BALL_LEFT_FIELD_TOUCH_LINE": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_CRASH_DRAWN": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_CRASH_UNIQUE": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_CRASH_UNIQUE_SKIPPED": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_DRIBBLED_BALL_TOO_FAR": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_HELD_BALL_DELIBERATELY": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_INTERFERED_PLACEMENT": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_KICKED_BALL_TOO_FAST": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_PUSHED_BOT": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_PUSHED_BOT_SKIPPED": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_SUBSTITUTION": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_TIPPED_OVER": "GAME_EVENT_BEHAVIOR_ON",
    "BOT_TOO_FAST_IN_STOP": "GAME_EVENT_BEHAVIOR_ON",
    "BOUNDARY_CROSSING": "GAME_EVENT_BEHAVIOR_ON",
    "CHIPPED_GOAL": "GAME_EVENT_BEHAVIOR_ON",
    "DEFENDER_IN_DEFENSE_AREA": "GAME_EVENT_BEHAVIOR_ON",
    "DEFENDER_IN_DEFENSE_AREA_PARTIALLY": "GAME_EVENT_BEHAVIOR_ON",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "GAME_EVENT_BEHAVIOR_ON",
    "GOAL": "GAME_EVENT_BEHAVIOR_ON",
    "INDIRECT_GOAL": "GAME_EVENT_BEHAVIOR_ON",
    "INVALID_GOAL": "GAME_EVENT_BEHAVIOR_ON",
    "KEEPER_HELD_BALL": "GAME_EVENT_BEHAVIOR_ON",
    "KICK_TIMEOUT": "GAME_EVENT_BEHAVIOR_ON",
    "MULTIPLE_CARDS": "GAME_EVENT_BEHAVIOR_ON",
    "MULTIPLE_FOULS": "GAME_EVENT_BEHAVIOR_ON",
    "MULTIPLE_PLACEMENT_FAILURES": "GAME_EVENT_BEHAVIOR_ON",
    "NO_PROGRESS_IN_GAME": "GAME_EVENT_BEHAVIOR_ON",
    "PENALTY_KICK_FAILED": "GAME_EVENT_BEHAVIOR_ON",
    "PLACEMENT_FAILED": "GAME_EVENT_BEHAVIOR_ON",
    "PLACEMENT_SUCCEEDED": "GAME_EVENT_BEHAVIOR_ON",
    "POSSIBLE_GOAL": "GAME_EVENT_BEHAVIOR_ON",
    "PREPARED": "GAME_EVENT_BEHAVIOR_ON",
    "TOO_MANY_ROBOTS": "GAME_EVENT_BEHAVIOR_ON",
    "UNKNOWN_GAME_EVENT_TYPE": "GAME_EVENT_BEHAVIOR_ON",
    "UNSPORTING_BEHAVIOR_MAJOR": "GAME_EVENT_BEHAVIOR_ON",
    "UNSPORTING_BEHAVIOR_MINOR": "GAME_EVENT_BEHAVIOR_ON"
  },
  "autoRefConfigs": {
  }
}